# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
  - repository: SREWeb
    type: git
    name: SREWeb
  
steps:
- checkout: SREWeb
- template: PipelineTemplates/Dotnetbuildtemplate.yaml@SREWeb
  parameters:
    buildConfiguration: 'Release'